### ISSUE TITLE
not able to save hdf5

### ISSUE THREAD

**Issue by deepcode-debug** [laddie132/MRC-PyTorch#2]
I am getting this error while running pre-process, can you please check?

2018-08-02 18:50:57,367 - [preprocess_data.py:375-run()] - INFO - padding id vectors...
2018-08-02 18:51:21,268 - [preprocess_data.py:392-run()] - INFO - export to hdf5 file...
Traceback (most recent call last):
  File "./run.py", line 35, in <module>
    preprocess(args.config_path)
  File "./run.py", line 24, in preprocess
    pdata.run()
  File "/data/dchaudhu/Match-LSTM/dataset/preprocess_data.py", line 393, in run
    self._export_squad_hdf5()
  File "/data/dchaudhu/Match-LSTM/dataset/preprocess_data.py", line 344, in _export_squad_hdf5
    **self._compress_option)
  File "/data/dchaudhu/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/_hl/group.py", line 116, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/data/dchaudhu/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 100, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1611, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1688, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

Regards,
Debanjan

**Comment by laddie132** [comment]
Sorry, I have not encountered such a problem. 
You can check the value of `sub_value.dtype` in `/data/dchaudhu/Match-LSTM/dataset/preprocess_data.py`, line 342.  
Did you set some options `False` in `global_config.yaml`? like `use_char `, `use_pos `.
