### ISSUE TITLE
prepocess_data.py 343行报错<data = data_grp.create_dataset>，哪里问题呢

### ISSUE THREAD

**Issue by MLjian** [laddie132/MRC-PyTorch#3]
`Traceback (most recent call last):
  File "run.py", line 35, in <module>
    preprocess(args.config_path)
  File "run.py", line 24, in preprocess
    pdata.run()
  File "E:\coms\challenger\资料\codes\Match-LSTM-master\Match-LSTM-master\dataset\preprocess_data.py", line 392, in run
    self._export_squad_hdf5()
  File "E:\coms\challenger\资料\codes\Match-LSTM-master\Match-LSTM-master\dataset\preprocess_data.py", line 343, in _export_squad_hdf5
    **self._compress_option)
  File "C:\Users\l\Anaconda3\lib\site-packages\h5py\_hl\group.py", line 106, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Users\l\Anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 100, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1519, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1541, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1596, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent'

**Comment by laddie132** [comment]
抱歉，我还没有遇到这样的问题，请检查文件`Match-LSTM-master\dataset\preprocess_data.py`第342行的`sub_value.dtype`

**Comment by MLjian** [comment]
好的，我再仔细找找。代码写的很攒！你应该将仓库名字改了，改成r-net什么之类的，看到的人也许会更多。

**Comment by laddie132** [comment]
:) 谢谢~ 如果找到某处bug，还望提醒。 目前R-Net复现效果比较差，只建议参考Match-LSTM部分

**Comment by MLjian** [comment]
你好，我看你的数据预处理应该是每个batch的最大句子长度都是不同。这样的话，网络模型在每个batch的时候，结构都是变化的，为什么不考虑，所有样本都padding到一样的长度呢?

**Comment by laddie132** [comment]
1. 使用PyTorch的PackedSequence处理后，会自动对每个batch缩减到合理的长度。
2. 考虑到SQuAD数据集中，段落长度分布比较广，0-700都存在，所有的样本padding到相同长度，计算资源耗费太大。
